server:
  port: 9008
spring:
  application:
    name: tensquare-user #指定服务名
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.0.0.1:3306/tensquare_user?characterEncoding=UTF8
    username: root
    password: 123456
  redis:
    host: 172.0.0.1
  rabbitmq:
    host: 192.168.5.5
  jpa:
    database: MySQL
    show-sql: true
jwt:
  config:
    key: itcast
    ttl: 3600000
eureka:
  client:
    service‐url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true