server:
  port: 9005
spring:
  application:
    name: tensquare-gathering #指定服务名
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.5.5:3306/db_gathering?characterEncoding=UTF8
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
